services:
  postgres-liquibase:
    image: postgres:16
    ports:
      - "5433:5433"
    environment:
      POSTGRES_USER: lb
      POSTGRES_PASSWORD: pass123
      POSTGRES_DB: lb_example

  postgres-flyway:
    image: postgres:16
    ports:
      - "5434:5434"
    environment:
      POSTGRES_USER: fly
      POSTGRES_PASSWORD: pass123
      POSTGRES_DB: fly_example