name: Flyway CI/CD

on:
  push:
    branches:
      - main

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Flyway
        run: |
          curl -L https://repo1.maven.org/maven2/org/flywaydb/flyway-commandline/9.16.0/flyway-commandline-9.16.0-linux-x64.tar.gz | tar xz
          export PATH="$PATH:$PWD/flyway-9.16.0"
      - name: Validate Database (Test)
        run: |
          ./flyway -url=jdbc:postgresql://test-db-host:5432/testdb -user=myuser -password=mypassword -locations=filesystem:flyway/sql validate

  test:
    runs-on: ubuntu-latest
    needs: validate
    steps:
      - uses: actions/checkout@v2
      - name: Setup Flyway
        run: |
          curl -L https://repo1.maven.org/maven2/org/flywaydb/flyway-commandline/9.16.0/flyway-commandline-9.16.0-linux-x64.tar.gz | tar xz
          export PATH="$PATH:$PWD/flyway-9.16.0"
      - name: Apply Changes (Test Database)
        run: |
          ./flyway -url=jdbc:postgresql://test-db-host:5432/testdb -user=myuser -password=mypassword -locations=filesystem:flyway/sql migrate

  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v2
      - name: Setup Flyway
        run: |
          curl -L https://repo1.maven.org/maven2/org/flywaydb/flyway-commandline/9.16.0/flyway-commandline-9.16.0-linux-x64.tar.gz | tar xz
          export PATH="$PATH:$PWD/flyway-9.16.0"
      - name: Apply Changes (Production Database)
        run: |
          ./flyway -url=jdbc:postgresql://prod-db-host:5432/proddb -user=myuser -password=mypassword -locations=filesystem:flyway/sql migrate
